import json
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterator

from sqlalchemy import Engine, create_engine, text
from sqlalchemy.engine import Connection

from app.core.config import settings


TERMINAL_UPLOAD_ITEM_STATUSES = ("indexed", "duplicate", "failed")
PROCESSING_UPLOAD_ITEM_STATUSES = ("queued", "saving", "parsing", "splitting", "embedding")

_engine: Engine | None = None
_engine_url: str | None = None
SCHEMA_VERSION = 3

_TIMESTAMP_COLUMNS = (
    ("documents", "created_at", False),
    ("documents", "updated_at", False),
    ("messages", "created_at", False),
    ("upload_batches", "created_at", False),
    ("upload_batches", "completed_at", True),
    ("upload_batch_items", "created_at", False),
    ("upload_batch_items", "updated_at", False),
    ("document_fingerprints", "created_at", False),
    ("document_fingerprints", "updated_at", False),
)


def _normalized_database_url() -> str:
    """读取并规范 PostgreSQL URL，不提供 SQLite fallback。"""
    database_url = settings.database_url.strip()
    if not database_url:
        raise RuntimeError(
            "DATABASE_URL is required. Configure a PostgreSQL URL such as "
            "postgresql+psycopg://user:password@localhost:5432/rag."
        )

    if database_url.startswith("postgresql://"):
        return "postgresql+psycopg://" + database_url[len("postgresql://") :]
    if not database_url.startswith("postgresql+psycopg://"):
        raise RuntimeError("DATABASE_URL must use PostgreSQL with the psycopg driver.")
    return database_url


def get_database_engine() -> Engine:
    """返回带连接池的 PostgreSQL Engine；配置变化时重建连接池。"""
    global _engine, _engine_url

    database_url = _normalized_database_url()
    if _engine is not None and _engine_url == database_url:
        return _engine

    if _engine is not None:
        _engine.dispose()

    _engine = create_engine(
        database_url,
        pool_pre_ping=True,
        pool_size=settings.database_pool_size,
        max_overflow=settings.database_max_overflow,
        pool_timeout=settings.database_pool_timeout,
        pool_recycle=settings.database_pool_recycle,
        connect_args={
            "connect_timeout": settings.database_connect_timeout,
            "application_name": "enterprise-rag-agent",
            "options": f"-c statement_timeout={settings.database_statement_timeout_ms}",
        },
    )
    _engine_url = database_url
    return _engine


def dispose_database_engine() -> None:
    """释放连接池，测试切换数据库 URL 时使用。"""
    global _engine, _engine_url
    if _engine is not None:
        _engine.dispose()
    _engine = None
    _engine_url = None


@contextmanager
def _connect() -> Iterator[Connection]:
    """开启一个短事务；正常退出提交，异常退出回滚。"""
    with get_database_engine().begin() as connection:
        yield connection


def check_database_connection() -> None:
    """启动和健康检查使用的最小 PostgreSQL 连通性检查。"""
    with _connect() as connection:
        connection.execute(text("SELECT 1"))


def init_db() -> None:
    """初始化 PostgreSQL 业务表，并执行幂等的版本化 schema 迁移。"""
    table_definitions = [
        """
        CREATE TABLE IF NOT EXISTS documents (
            document_id TEXT PRIMARY KEY,
            filename TEXT NOT NULL,
            file_type TEXT NOT NULL,
            file_path TEXT NOT NULL,
            chunk_count INTEGER NOT NULL,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            thread_id TEXT NOT NULL,
            role TEXT NOT NULL,
            content TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS upload_batches (
            batch_id TEXT PRIMARY KEY,
            status TEXT NOT NULL,
            total INTEGER NOT NULL,
            succeeded INTEGER NOT NULL DEFAULT 0,
            failed INTEGER NOT NULL DEFAULT 0,
            skipped INTEGER NOT NULL DEFAULT 0,
            graph_path JSONB NOT NULL DEFAULT '[]'::jsonb,
            duration_ms INTEGER NOT NULL DEFAULT 0,
            created_at TIMESTAMPTZ NOT NULL,
            completed_at TIMESTAMPTZ
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS upload_batch_items (
            item_id TEXT PRIMARY KEY,
            batch_id TEXT NOT NULL,
            item_order INTEGER NOT NULL DEFAULT 0,
            document_id TEXT,
            filename TEXT NOT NULL,
            file_type TEXT NOT NULL,
            file_hash TEXT,
            file_path TEXT,
            status TEXT NOT NULL,
            error_stage TEXT,
            error_message TEXT,
            chunk_count INTEGER NOT NULL DEFAULT 0,
            duration_ms INTEGER NOT NULL DEFAULT 0,
            retry_count INTEGER NOT NULL DEFAULT 0,
            duplicate_of_document_id TEXT,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL,
            FOREIGN KEY (batch_id) REFERENCES upload_batches(batch_id) ON DELETE CASCADE
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS document_fingerprints (
            file_hash TEXT PRIMARY KEY,
            document_id TEXT NOT NULL,
            status TEXT NOT NULL,
            filename TEXT NOT NULL,
            file_path TEXT,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS schema_migrations (
            version INTEGER PRIMARY KEY,
            applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """,
    ]

    with _connect() as connection:
        for definition in table_definitions:
            connection.execute(text(definition))
        _apply_schema_migrations(connection)
    mark_interrupted_uploads()


def _column_data_type(connection: Connection, table_name: str, column_name: str) -> str | None:
    row = connection.execute(
        text(
            """
            SELECT data_type
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = :table_name
              AND column_name = :column_name
            """
        ),
        {"table_name": table_name, "column_name": column_name},
    ).scalar_one_or_none()
    return str(row) if row is not None else None


def _convert_timestamp_column(
    connection: Connection,
    table_name: str,
    column_name: str,
    nullable: bool,
) -> None:
    if _column_data_type(connection, table_name, column_name) != "text":
        return

    if nullable:
        expression = f"NULLIF({column_name}, '')::timestamptz"
    else:
        expression = f"COALESCE(NULLIF({column_name}, '')::timestamptz, now())"
    connection.execute(
        text(
            f"ALTER TABLE {table_name} ALTER COLUMN {column_name} "
            f"TYPE TIMESTAMPTZ USING {expression}"
        )
    )


def _add_check_constraint(
    connection: Connection,
    table_name: str,
    constraint_name: str,
    expression: str,
) -> None:
    connection.execute(
        text(
            f"""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = '{constraint_name}'
                ) THEN
                    ALTER TABLE {table_name}
                    ADD CONSTRAINT {constraint_name} CHECK ({expression});
                END IF;
            END $$;
            """
        )
    )


def _apply_schema_migrations(connection: Connection) -> None:
    current_version = connection.execute(
        text("SELECT COALESCE(MAX(version), 0) FROM schema_migrations")
    ).scalar_one()
    if int(current_version) >= SCHEMA_VERSION:
        return

    # Existing v0.4 databases used TEXT timestamps and stored graph_path as JSON text.
    # Convert them in place so the application can be upgraded without data loss.
    connection.execute(
        text("ALTER TABLE documents ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ")
    )
    connection.execute(
        text("ALTER TABLE upload_batch_items ADD COLUMN IF NOT EXISTS item_order INTEGER")
    )
    connection.execute(
        text(
            """
            WITH ordered_items AS (
                SELECT item_id,
                       ROW_NUMBER() OVER (
                           PARTITION BY batch_id ORDER BY created_at, item_id
                       ) - 1 AS item_order
                FROM upload_batch_items
            )
            UPDATE upload_batch_items AS items
            SET item_order = ordered_items.item_order
            FROM ordered_items
            WHERE items.item_id = ordered_items.item_id
            """
        )
    )
    connection.execute(
        text("ALTER TABLE upload_batch_items ALTER COLUMN item_order SET DEFAULT 0")
    )
    connection.execute(
        text("ALTER TABLE upload_batch_items ALTER COLUMN item_order SET NOT NULL")
    )
    for table_name, column_name, nullable in _TIMESTAMP_COLUMNS:
        _convert_timestamp_column(connection, table_name, column_name, nullable)

    connection.execute(
        text(
            """
            UPDATE documents
            SET updated_at = COALESCE(updated_at, created_at)
            WHERE updated_at IS NULL
            """
        )
    )
    connection.execute(text("ALTER TABLE documents ALTER COLUMN updated_at SET NOT NULL"))

    if _column_data_type(connection, "upload_batches", "graph_path") == "text":
        connection.execute(
            text("ALTER TABLE upload_batches ALTER COLUMN graph_path DROP DEFAULT")
        )
        connection.execute(
            text(
                "ALTER TABLE upload_batches ALTER COLUMN graph_path TYPE JSONB "
                "USING COALESCE(NULLIF(graph_path, ''), '[]')::jsonb"
            )
        )
    connection.execute(
        text("ALTER TABLE upload_batches ALTER COLUMN graph_path SET DEFAULT '[]'::jsonb")
    )

    # Normalize legacy values before adding constraints.
    connection.execute(
        text(
            "UPDATE upload_batches SET status = 'failed' "
            "WHERE status NOT IN ('running', 'completed', 'partial_success', 'failed')"
        )
    )
    connection.execute(
        text(
            "UPDATE upload_batch_items SET status = 'failed', "
            "error_stage = COALESCE(error_stage, 'schema_migration'), "
            "error_message = COALESCE(error_message, 'Unknown legacy upload status.') "
            "WHERE status NOT IN ('queued', 'saving', 'parsing', 'splitting', 'embedding', "
            "'indexed', 'duplicate', 'failed')"
        )
    )
    connection.execute(
        text(
            "UPDATE document_fingerprints SET status = 'failed' "
            "WHERE status NOT IN ('processing', 'indexed', 'failed')"
        )
    )

    _add_check_constraint(
        connection,
        "upload_batches",
        "ck_upload_batches_status",
        "status IN ('running', 'completed', 'partial_success', 'failed')",
    )
    _add_check_constraint(
        connection,
        "upload_batch_items",
        "ck_upload_batch_items_status",
        "status IN ('queued', 'saving', 'parsing', 'splitting', 'embedding', 'indexed', 'duplicate', 'failed')",
    )
    _add_check_constraint(
        connection,
        "document_fingerprints",
        "ck_document_fingerprints_status",
        "status IN ('processing', 'indexed', 'failed')",
    )

    indexes = (
        "CREATE INDEX IF NOT EXISTS idx_documents_created_at ON documents(created_at DESC)",
        "CREATE INDEX IF NOT EXISTS idx_messages_thread_id_id ON messages(thread_id, id DESC)",
        "CREATE INDEX IF NOT EXISTS idx_upload_batch_items_batch_status "
        "ON upload_batch_items(batch_id, status)",
        "CREATE INDEX IF NOT EXISTS idx_document_fingerprints_document_id "
        "ON document_fingerprints(document_id)",
        "CREATE INDEX IF NOT EXISTS idx_upload_batches_status_created_at "
        "ON upload_batches(status, created_at DESC)",
    )
    for definition in indexes:
        connection.execute(text(definition))

    connection.execute(
        text(
            "INSERT INTO schema_migrations(version) VALUES (:version) "
            "ON CONFLICT (version) DO NOTHING"
        ),
        {"version": SCHEMA_VERSION},
    )


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _duration_ms(created_at: str | datetime | None) -> int:
    try:
        started = (
            created_at
            if isinstance(created_at, datetime)
            else datetime.fromisoformat(created_at or "")
        )
        if started.tzinfo is None:
            started = started.replace(tzinfo=timezone.utc)
        return max(0, int((datetime.now(timezone.utc) - started).total_seconds() * 1000))
    except (TypeError, ValueError):
        return 0


def _row_dict(row: Any) -> dict[str, Any] | None:
    if row is None:
        return None
    # SQLAlchemy 2.x 的 Row 需要从 _mapping 转成字典；RowMapping 本身也兼容该写法。
    result = dict(getattr(row, "_mapping", row))
    for key in ("created_at", "updated_at", "completed_at"):
        value = result.get(key)
        if isinstance(value, datetime):
            result[key] = value.isoformat()
    return result


def _rows_dict(rows: Any) -> list[dict[str, Any]]:
    return [_row_dict(row) for row in rows]


def save_document(
    document_id: str,
    filename: str,
    file_type: str,
    file_path: Path,
    chunk_count: int,
) -> None:
    """保存成功入库的文档信息；向量内容存在 Chroma。"""
    now = utc_now()
    with _connect() as connection:
        connection.execute(
            text(
                """
                INSERT INTO documents
                (document_id, filename, file_type, file_path, chunk_count, created_at, updated_at)
                VALUES (:document_id, :filename, :file_type, :file_path, :chunk_count,
                        :created_at, :updated_at)
                ON CONFLICT (document_id) DO UPDATE SET
                    filename = EXCLUDED.filename,
                    file_type = EXCLUDED.file_type,
                    file_path = EXCLUDED.file_path,
                    chunk_count = EXCLUDED.chunk_count,
                    updated_at = EXCLUDED.updated_at
                """
            ),
            {
                "document_id": document_id,
                "filename": filename,
                "file_type": file_type,
                "file_path": str(file_path),
                "chunk_count": chunk_count,
                "created_at": now,
                "updated_at": now,
            },
        )


def get_document(document_id: str) -> dict[str, Any] | None:
    with _connect() as connection:
        row = connection.execute(
            text(
                """
                SELECT document_id, filename, file_type, file_path, chunk_count, created_at
                FROM documents
                WHERE document_id = :document_id
                """
            ),
            {"document_id": document_id},
        ).mappings().first()
    return _row_dict(row)


def delete_document_record(document_id: str) -> dict[str, Any] | None:
    """删除 PostgreSQL 中的文档记录和对应指纹，返回删除前的文档信息。"""
    with _connect() as connection:
        row = connection.execute(
            text("SELECT * FROM documents WHERE document_id = :document_id"),
            {"document_id": document_id},
        ).mappings().first()
        if not row:
            return None
        connection.execute(
            text("DELETE FROM documents WHERE document_id = :document_id"),
            {"document_id": document_id},
        )
        connection.execute(
            text("DELETE FROM document_fingerprints WHERE document_id = :document_id"),
            {"document_id": document_id},
        )
    return _row_dict(row)


def list_documents() -> list[dict]:
    """给文档列表接口和 Agent 工具使用。"""
    with _connect() as connection:
        rows = connection.execute(
            text(
                """
                SELECT document_id, filename, file_type, chunk_count, created_at
                FROM documents
                ORDER BY created_at DESC
                """
            )
        ).mappings().all()
    return _rows_dict(rows)


def count_documents() -> int:
    with _connect() as connection:
        row = connection.execute(text("SELECT COUNT(*) AS count FROM documents")).mappings().first()
    return int(row["count"])


def clear_documents() -> int:
    """清空文档元数据，并返回删除数量。"""
    with _connect() as connection:
        row = connection.execute(text("SELECT COUNT(*) AS count FROM documents")).mappings().first()
        removed_count = int(row["count"])
        connection.execute(text("DELETE FROM documents"))
    return removed_count


def save_message(thread_id: str, role: str, content: str) -> None:
    """保存一条对话消息，thread_id 用来区分不同会话。"""
    with _connect() as connection:
        connection.execute(
            text(
                """
                INSERT INTO messages (thread_id, role, content, created_at)
                VALUES (:thread_id, :role, :content, :created_at)
                """
            ),
            {
                "thread_id": thread_id,
                "role": role,
                "content": content,
                "created_at": utc_now(),
            },
        )


def get_messages(thread_id: str, limit: int = 8) -> list[dict]:
    """读取最近几轮对话，返回时恢复为从旧到新的顺序。"""
    with _connect() as connection:
        rows = connection.execute(
            text(
                """
                SELECT role, content, created_at
                FROM messages
                WHERE thread_id = :thread_id
                ORDER BY id DESC
                LIMIT :limit
                """
            ),
            {"thread_id": thread_id, "limit": limit},
        ).mappings().all()
    return list(reversed(_rows_dict(rows)))


def clear_messages() -> int:
    """清空所有会话历史，并返回删除数量。"""
    with _connect() as connection:
        row = connection.execute(text("SELECT COUNT(*) AS count FROM messages")).mappings().first()
        removed_count = int(row["count"])
        connection.execute(text("DELETE FROM messages"))
    return removed_count


def create_upload_batch(batch_id: str, total: int) -> None:
    now = utc_now()
    with _connect() as connection:
        connection.execute(
            text(
                """
                INSERT INTO upload_batches (batch_id, status, total, created_at)
                VALUES (:batch_id, 'running', :total, :created_at)
                """
            ),
            {"batch_id": batch_id, "total": total, "created_at": now},
        )


def create_upload_batch_with_items(
    batch_id: str,
    items: list[dict[str, Any]],
) -> None:
    """原子创建批次和全部 item，避免进程在预处理阶段留下缺 item 的 running 批次。"""
    now = utc_now()
    with _connect() as connection:
        connection.execute(
            text(
                """
                INSERT INTO upload_batches (batch_id, status, total, created_at)
                VALUES (:batch_id, 'running', :total, :created_at)
                """
            ),
            {"batch_id": batch_id, "total": len(items), "created_at": now},
        )
        connection.execute(
            text(
                """
                INSERT INTO upload_batch_items
                (item_id, batch_id, item_order, filename, file_type, status, created_at, updated_at)
                VALUES (:item_id, :batch_id, :item_order, :filename, :file_type,
                        'queued', :created_at, :updated_at)
                """
            ),
            [
                {
                    "item_id": item["item_id"],
                    "batch_id": batch_id,
                    "item_order": int(item.get("item_order", index)),
                    "filename": item["filename"],
                    "file_type": item["file_type"],
                    "created_at": now,
                    "updated_at": now,
                }
                for index, item in enumerate(items)
            ],
        )


def create_upload_batch_item(
    item_id: str,
    batch_id: str,
    filename: str,
    file_type: str,
) -> None:
    now = utc_now()
    with _connect() as connection:
        item_order = connection.execute(
            text(
                "SELECT COALESCE(MAX(item_order), -1) + 1 "
                "FROM upload_batch_items WHERE batch_id = :batch_id"
            ),
            {"batch_id": batch_id},
        ).scalar_one()
        connection.execute(
            text(
                """
                INSERT INTO upload_batch_items
                (item_id, batch_id, item_order, filename, file_type, status, created_at, updated_at)
                VALUES (:item_id, :batch_id, :item_order, :filename, :file_type,
                        'queued', :created_at, :updated_at)
                """
            ),
            {
                "item_id": item_id,
                "batch_id": batch_id,
                "item_order": int(item_order),
                "filename": filename,
                "file_type": file_type,
                "created_at": now,
                "updated_at": now,
            },
        )


def update_upload_batch_item(item_id: str, **fields: Any) -> None:
    """更新单个文件的处理状态；字段名来自内部白名单，避免拼接任意 SQL。"""
    allowed = {
        "document_id",
        "file_hash",
        "file_path",
        "status",
        "error_stage",
        "error_message",
        "chunk_count",
        "duration_ms",
        "retry_count",
        "duplicate_of_document_id",
    }
    updates = {key: value for key, value in fields.items() if key in allowed}
    if not updates:
        return
    updates["updated_at"] = utc_now()
    assignments = ", ".join(f"{key} = :{key}" for key in updates)
    params = {**updates, "item_id": item_id}
    with _connect() as connection:
        connection.execute(
            text(f"UPDATE upload_batch_items SET {assignments} WHERE item_id = :item_id"),
            params,
        )


def get_upload_batch_item(item_id: str) -> dict[str, Any] | None:
    with _connect() as connection:
        row = connection.execute(
            text("SELECT * FROM upload_batch_items WHERE item_id = :item_id"),
            {"item_id": item_id},
        ).mappings().first()
    return _row_dict(row)


def refresh_upload_batch(batch_id: str, graph_path: list[str] | None = None) -> dict[str, Any]:
    """根据 item 状态重新计算批次汇总，避免手工计数产生不一致。"""
    with _connect() as connection:
        batch = connection.execute(
            text("SELECT * FROM upload_batches WHERE batch_id = :batch_id FOR UPDATE"),
            {"batch_id": batch_id},
        ).mappings().first()
        if not batch:
            raise KeyError(f"Upload batch not found: {batch_id}")

        items = connection.execute(
            text("SELECT status FROM upload_batch_items WHERE batch_id = :batch_id"),
            {"batch_id": batch_id},
        ).mappings().all()
        statuses = [row["status"] for row in items]
        succeeded = statuses.count("indexed")
        failed = statuses.count("failed")
        skipped = statuses.count("duplicate")
        finished = len(statuses) == int(batch["total"]) and all(
            status in TERMINAL_UPLOAD_ITEM_STATUSES for status in statuses
        )

        if not finished:
            status = "running"
            completed_at = None
        elif failed == int(batch["total"]):
            status = "failed"
            completed_at = utc_now()
        elif failed and succeeded:
            status = "partial_success"
            completed_at = utc_now()
        elif failed:
            status = "failed"
            completed_at = utc_now()
        else:
            status = "completed"
            completed_at = utc_now()

        path_value = batch["graph_path"] if graph_path is None else graph_path
        path_text = json.dumps(path_value or [], ensure_ascii=False)

        duration_ms = _duration_ms(batch["created_at"]) if finished else 0
        connection.execute(
            text(
                """
                UPDATE upload_batches
                SET status = :status, succeeded = :succeeded, failed = :failed,
                    skipped = :skipped, graph_path = :graph_path,
                    duration_ms = :duration_ms, completed_at = :completed_at
                WHERE batch_id = :batch_id
                """
            ),
            {
                "status": status,
                "succeeded": succeeded,
                "failed": failed,
                "skipped": skipped,
                "graph_path": path_text,
                "duration_ms": duration_ms,
                "completed_at": completed_at,
                "batch_id": batch_id,
            },
        )

    result = get_upload_batch(batch_id)
    if result is None:
        raise KeyError(f"Upload batch not found after refresh: {batch_id}")
    return result


def get_upload_batch(batch_id: str) -> dict[str, Any] | None:
    with _connect() as connection:
        batch = connection.execute(
            text("SELECT * FROM upload_batches WHERE batch_id = :batch_id"),
            {"batch_id": batch_id},
        ).mappings().first()
        if not batch:
            return None
        items = connection.execute(
            text(
                """
                SELECT item_id, batch_id, document_id, filename, file_type, file_hash,
                       file_path, status, error_stage, error_message, chunk_count,
                       duration_ms, retry_count, duplicate_of_document_id,
                       created_at, updated_at
                FROM upload_batch_items
                WHERE batch_id = :batch_id
                ORDER BY item_order, created_at, item_id
                """
            ),
            {"batch_id": batch_id},
        ).mappings().all()

    result = _row_dict(batch)
    graph_path = result.get("graph_path")
    if isinstance(graph_path, str):
        graph_path = json.loads(graph_path or "[]")
    result["graph_path"] = graph_path or []
    result["items"] = _rows_dict(items)
    return result


def list_upload_batches(limit: int = 20) -> list[dict[str, Any]]:
    safe_limit = max(1, min(limit, 100))
    with _connect() as connection:
        rows = connection.execute(
            text(
                """
                SELECT batch_id, status, total, succeeded, failed, skipped,
                       duration_ms, created_at, completed_at
                FROM upload_batches
                ORDER BY created_at DESC
                LIMIT :limit
                """
            ),
            {"limit": safe_limit},
        ).mappings().all()
    return _rows_dict(rows)


def reserve_document_fingerprint(
    file_hash: str,
    document_id: str,
    filename: str,
    file_path: Path,
) -> dict[str, Any]:
    """原子地登记文件指纹，保证同一内容不会被并发重复处理。"""
    now = utc_now()
    with _connect() as connection:
        inserted = connection.execute(
            text(
                """
                INSERT INTO document_fingerprints
                (file_hash, document_id, status, filename, file_path, created_at, updated_at)
                VALUES (:file_hash, :document_id, 'processing', :filename, :file_path, :created_at, :updated_at)
                ON CONFLICT (file_hash) DO NOTHING
                RETURNING file_hash, document_id, status, filename, file_path
                """
            ),
            {
                "file_hash": file_hash,
                "document_id": document_id,
                "filename": filename,
                "file_path": str(file_path),
                "created_at": now,
                "updated_at": now,
            },
        ).mappings().first()
        if inserted:
            return {
                "reserved": True,
                "document_id": inserted["document_id"],
                "status": "processing",
            }

        reclaimed = connection.execute(
            text(
                """
                UPDATE document_fingerprints
                SET document_id = :document_id, status = 'processing',
                    filename = :filename, file_path = :file_path, updated_at = :updated_at
                WHERE file_hash = :file_hash AND status = 'failed'
                RETURNING document_id
                """
            ),
            {
                "file_hash": file_hash,
                "document_id": document_id,
                "filename": filename,
                "file_path": str(file_path),
                "updated_at": now,
            },
        ).mappings().first()
        if reclaimed:
            return {
                "reserved": True,
                "document_id": reclaimed["document_id"],
                "status": "processing",
                "reclaimed": True,
            }

        row = connection.execute(
            text("SELECT * FROM document_fingerprints WHERE file_hash = :file_hash"),
            {"file_hash": file_hash},
        ).mappings().first()
        if not row:
            raise RuntimeError("Fingerprint reservation disappeared before it could be read.")
        return {
            "reserved": False,
            "document_id": row["document_id"],
            "status": row["status"],
            "filename": row["filename"],
            "file_path": row["file_path"],
        }


def set_document_fingerprint_status(file_hash: str, status: str, file_path: Path | None = None) -> None:
    now = utc_now()
    with _connect() as connection:
        if file_path is None:
            connection.execute(
                text(
                    "UPDATE document_fingerprints "
                    "SET status = :status, updated_at = :updated_at "
                    "WHERE file_hash = :file_hash"
                ),
                {"status": status, "updated_at": now, "file_hash": file_hash},
            )
        else:
            connection.execute(
                text(
                    "UPDATE document_fingerprints "
                    "SET status = :status, file_path = :file_path, updated_at = :updated_at "
                    "WHERE file_hash = :file_hash"
                ),
                {
                    "status": status,
                    "file_path": str(file_path),
                    "updated_at": now,
                    "file_hash": file_hash,
                },
            )


def get_document_fingerprint(document_id: str) -> dict[str, Any] | None:
    with _connect() as connection:
        row = connection.execute(
            text("SELECT * FROM document_fingerprints WHERE document_id = :document_id"),
            {"document_id": document_id},
        ).mappings().first()
    return _row_dict(row)


def upsert_document_fingerprint(
    file_hash: str,
    document_id: str,
    filename: str,
    file_path: Path,
    status: str = "processing",
) -> None:
    """为旧数据或重建索引任务补登记指纹。"""
    now = utc_now()
    with _connect() as connection:
        connection.execute(
            text(
                """
                INSERT INTO document_fingerprints
                (file_hash, document_id, status, filename, file_path, created_at, updated_at)
                VALUES (:file_hash, :document_id, :status, :filename, :file_path, :created_at, :updated_at)
                ON CONFLICT (file_hash) DO UPDATE SET
                    document_id = EXCLUDED.document_id,
                    status = EXCLUDED.status,
                    filename = EXCLUDED.filename,
                    file_path = EXCLUDED.file_path,
                    updated_at = EXCLUDED.updated_at
                """
            ),
            {
                "file_hash": file_hash,
                "document_id": document_id,
                "status": status,
                "filename": filename,
                "file_path": str(file_path),
                "created_at": now,
                "updated_at": now,
            },
        )


def clear_upload_tracking() -> None:
    with _connect() as connection:
        connection.execute(text("DELETE FROM document_fingerprints"))
        connection.execute(text("DELETE FROM upload_batch_items"))
        connection.execute(text("DELETE FROM upload_batches"))


def mark_interrupted_uploads() -> None:
    """应用重启后，把未完成的本地任务标记为可重试的失败状态。"""
    status_params = {f"status_{index}": status for index, status in enumerate(PROCESSING_UPLOAD_ITEM_STATUSES)}
    status_placeholders = ", ".join(f":{key}" for key in status_params)
    batch_ids: list[str] = []
    with _connect() as connection:
        running_batches = connection.execute(
            text("SELECT batch_id FROM upload_batches WHERE status = 'running'")
        ).mappings().all()
        batch_ids = [row["batch_id"] for row in running_batches]
        rows = connection.execute(
            text(
                "SELECT DISTINCT batch_id FROM upload_batch_items "
                f"WHERE status IN ({status_placeholders})"
            ),
            status_params,
        ).mappings().all()
        batch_ids.extend(row["batch_id"] for row in rows if row["batch_id"] not in batch_ids)
        connection.execute(
            text(
                "UPDATE upload_batch_items "
                "SET status = 'failed', error_stage = 'interrupted', "
                "error_message = :error_message, updated_at = :updated_at "
                f"WHERE status IN ({status_placeholders})"
            ),
            {
                **status_params,
                "error_message": "Application restarted before this file finished.",
                "updated_at": utc_now(),
            },
        )
        connection.execute(
            text(
                "UPDATE document_fingerprints SET status = 'failed', updated_at = :updated_at "
                "WHERE status = 'processing'"
            ),
            {"updated_at": utc_now()},
        )

    for batch_id in batch_ids:
        refresh_upload_batch(batch_id)
